#!/usr/bin/env python3
"""
Convert wrapper JSON output to PBN format for viewing in BridgeComposer.
"""
import json
import sys
import re

def parse_deal_for_dealer(deal):
    """Extract dealer from deal string. Returns S for standard format."""
    # Deal format: "N:hand1 hand2 hand3 hand4" - first char before : is first seat
    if ':' in deal:
        return deal[0]  # Usually 'N', meaning hands are listed N E S W
    return 'S'

def get_vulnerability(board_num):
    """Get vulnerability based on board number (standard rotation)."""
    vul_cycle = ['None', 'NS', 'EW', 'All', 'NS', 'EW', 'All', 'None',
                 'EW', 'All', 'None', 'NS', 'All', 'None', 'NS', 'EW']
    return vul_cycle[(board_num - 1) % 16]

def get_dealer(board_num):
    """Get dealer based on board number.
    Note: For 1NT scenarios, dealer is always South regardless of board number.
    """
    # For these test scenarios, dealer is always South
    return 'S'

def format_auction(bids, dealer):
    """Format auction for PBN. Add dashes for skipped positions if dealer isn't South."""
    # For now, assume dealer is always South (position 2)
    # PBN auction starts from dealer
    lines = []
    current_line = []

    for bid in bids:
        current_line.append(bid)
        if len(current_line) == 4:
            lines.append(' '.join(current_line))
            current_line = []

    if current_line:
        lines.append(' '.join(current_line))

    return '\n'.join(lines)

def main():
    if len(sys.argv) < 2:
        print("Usage: json_to_pbn.py <wrapper-output.json> [output.pbn]")
        sys.exit(1)

    json_file = sys.argv[1]
    pbn_file = sys.argv[2] if len(sys.argv) > 2 else json_file.replace('.json', '.pbn')

    with open(json_file, 'r') as f:
        data = json.load(f)

    with open(pbn_file, 'w') as f:
        f.write("% PBN 2.1\n")
        f.write("% Generated by epbot-wrapper\n\n")

        for i, result in enumerate(data['results'], 1):
            deal = result['deal']
            auction = result['auction']

            dealer = get_dealer(i)
            vul = get_vulnerability(i)

            f.write(f'[Event "EPBot Wrapper Test"]\n')
            f.write(f'[Site ""]\n')
            f.write(f'[Date ""]\n')
            f.write(f'[Board "{i}"]\n')
            f.write(f'[West "EPBot"]\n')
            f.write(f'[North "EPBot"]\n')
            f.write(f'[East "EPBot"]\n')
            f.write(f'[South "EPBot"]\n')
            f.write(f'[Dealer "{dealer}"]\n')
            f.write(f'[Vulnerable "{vul}"]\n')
            f.write(f'[Deal "{deal}"]\n')
            f.write(f'[Declarer "?"]\n')
            f.write(f'[Contract "?"]\n')
            f.write(f'[Result "?"]\n')
            f.write(f'[Auction "{dealer}"]\n')
            f.write(format_auction(auction, dealer) + '\n')
            f.write('\n')

    print(f"Created {pbn_file} with {len(data['results'])} deals")

if __name__ == '__main__':
    main()
